CREATE DATABASE IF NOT EXISTS JOB_PORTAL;

CREATE TABLE USER 
(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(250) NOT NULL,
    PASSWORD VARCHAR(250) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    ROLE VARCHAR(50) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PROFILE_PIC VARCHAR(255)
);

CREATE TABLE JOB
(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    TITLE VARCHAR(50) NOT NULL,
    DESCRIPTION TEXT NOT NULL,
    SALARY DECIMAL(10, 2) NOT NULL,
    LOCATION VARCHAR(50) NOT NULL,
    TYPE VARCHAR(50) NOT NULL,
    ARRANGEMENT VARCHAR(50) NOT NULL,
    USER_ID INT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);

CREATE TABLE APPLICATION
(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    APPLICANT_ID INT,
    JOB_ID INT,
    YEARS_OF_EXPERIENCE INT NOT NULL,
    MOTIVATION TEXT NOT NULL,
    APPLIED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (APPLICANT_ID) REFERENCES USER(ID),
    FOREIGN KEY (JOB_ID) REFERENCES JOB(ID)
);
