CREATE DATABASE IF NOT EXISTS JOB_PORTAL;
USE JOB_PORTAL;

CREATE TABLE USER 
(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    ROLE VARCHAR(50) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PROFILE_PIC VARCHAR(255)
);

CREATE TABLE JOB
(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    TITLE VARCHAR(50) NOT NULL,
    RESPONSIBILITIES TEXT NOT NULL,
    QUALIFICATIONS TEXT NOT NULL,
    SALARY DECIMAL(10, 2) NOT NULL,
    LOCATION VARCHAR(50) NOT NULL,
    INDUSTRY VARCHAR(50) NOT NULL,
    TYPE VARCHAR(50) NOT NULL,
    USER_ID INT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);

