CREATE DATABASE IF NOT EXISTS thewell;

CREATE TABLE STUDENT 
(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(250) NOT NULL,
    USERNAME VARCHAR(250) NOT NULL,
    EMAIL VARCHAR(250) NOT NULL,
    CLASS INT NOT NULL,
    MAJOR VARCHAR(250) NOT NULL,
    STUDENT_ID INT NOT NULL,
    PASSWORD VARCHAR(250) NOT NULL,
    AUTH_CODE INT,
    STATUS INT DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PROFILE_PIC VARCHAR(255)
);
